Repository School-of-Company/Gwangsan-Android, pull requests merged in 2025-07, with the labels that each got.

#91 🔀 :: #(90) - 로그인 API명세서가 수정되 전체적인 로그인 로직을 수정했습니다
  app/build.gradle.kts
  core/model/src/main/java/com/school_of_company/model/auth/request/LoginRequestModel.kt
  core/network/src/main/java/com/school_of_company/network/dto/auth/requset/LoginRequest.kt
  core/network/src/main/java/com/school_of_company/network/mapper/auth/request/LoginRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/util/DeviceIdManager.kt
  feature/signin/src/main/java/com/school_of_company/signin/view/SignInScreen.kt
  feature/signin/src/main/java/com/school_of_company/signin/viewmodel/SignInViewModel.kt
  gradle/libs.versions.toml
Labels: 1️⃣ Priority: High

#93 🔀 :: (#92) - :feature:content 모듈 리팩터링을 진행하였습니다.
  app/build.gradle.kts
  core/design-system/src/main/java/com/school_of_company/design_system/componet/recycle/CleaningRequestCard.kt
  core/design-system/src/main/java/com/school_of_company/design_system/componet/recycle/MyProfileUserLevel.kt
  feature/chat/build.gradle.kts
  feature/content/build.gradle.kts
  feature/content/src/main/java/com/school_of_company/content/component/RatingSlider.kt
  feature/content/src/main/java/com/school_of_company/content/component/ReportBottomSheet.kt
  feature/content/src/main/java/com/school_of_company/content/component/ReviewBottomSheet.kt
  feature/content/src/main/java/com/school_of_company/content/view/ContentScreen.kt
  feature/content/src/main/java/com/school_of_company/content/view/ReadMoreScreen.kt
  feature/content/src/main/java/com/school_of_company/content/view/ReportScreen.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#100 🔀 :: (#99) - :feature:main 모듈 리팩터링을 하였습니다.
  app/build.gradle.kts
  core/design-system/src/main/java/com/school_of_company/design_system/componet/dropdown/GwangSanSwitchButton.kt
  core/design-system/src/main/java/com/school_of_company/design_system/componet/icons/GwangSanIcon.kt
  core/design-system/src/main/res/drawable/mdi_shopping_outline.xml
  core/design-system/src/main/res/drawable/mingcute_service_line.xml
  core/design-system/src/main/res/font/cafe_24_ssroround.otf
  feature/main/src/main/java/com/school_of_company/main/component/MainButton.kt
  feature/main/src/main/java/com/school_of_company/main/view/MainScreen.kt
  feature/main/src/main/java/com/school_of_company/main/view/MainStartScreen.kt
  feature/signin/src/main/java/com/school_of_company/signin/view/StartScreen.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#109 🔀 :: (#108) - Post 파트 네트워크 세팅을 완료하였습니다.
  core/data/src/main/java/com/school_of_company/data/repository/post/PostRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/post/PostRepositoryImpl.kt
  core/model/src/main/java/com/school_of_company/model/post/request/PostAllRequestModel.kt
  core/model/src/main/java/com/school_of_company/model/post/request/PostModifyRequestModel.kt
  core/model/src/main/java/com/school_of_company/model/post/request/PostWriteRequestModel.kt
  core/model/src/main/java/com/school_of_company/model/post/response/PostListResponseModel.kt
  core/model/src/main/java/com/school_of_company/model/post/response/PostModifyResponseModel.kt
  core/network/src/main/java/com/school_of_company/network/api/PostAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/post/PostDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/post/PostDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/dto/post/request/PostAllRequest.kt
  core/network/src/main/java/com/school_of_company/network/dto/post/request/PostModifyRequest.kt
  core/network/src/main/java/com/school_of_company/network/dto/post/response/PostListResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/post/request/PostAllRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/post/request/PostModifyRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/post/request/PostWriteRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/post/response/PostListResponseMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/post/response/PostModifyResponseMapper.kt
  feature/post/src/main/java/com/school_of_company/post/viewmodel/PostViewModel.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚙ Setting

#111 🔀 :: (#110) - 커스텀 Preview를 제작하였습니다.
  core/ui/build.gradle.kts
  core/ui/src/androidTest/java/com/school_of_company/ui/ExampleInstrumentedTest.kt
  core/ui/src/main/java/com/school_of_company/ui/previews/GwangsanPreviews.kt
  feature/signup/src/main/java/com/school_of_company/signup/view/FinishScreen.kt
  settings.gradle.kts
Labels: 2️⃣ Priority: Medium, ✨ Feature

#117 🔀 :: (#113) - 네비게이션 세팅이 안된 부분을 세팅하고 NavHost에 추가했습니다.
  app/build.gradle.kts
  app/src/main/java/com/school_of_company/gwangsan_android/navigation/GwangSanNavHost.kt
  feature/chat/build.gradle.kts
  feature/chat/src/main/java/com/school_of_company/chat/navigation/ChatNavigation.kt
  feature/chat/src/main/java/com/school_of_company/chat/view/ChatRoomScreen.kt
  feature/chat/src/main/java/com/school_of_company/chat/view/ChatScreen.kt
  feature/content/build.gradle.kts
  feature/content/src/main/java/com/school_of_company/content/navigation/ContentNavigation.kt
  feature/inform/build.gradle.kts
  feature/inform/src/main/java/com/school_of_company/inform/navigation/InformNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/school_of_company/main/navgation/MainNavigation.kt
  feature/main/src/main/java/com/school_of_company/main/view/MainScreen.kt
  feature/main/src/main/java/com/school_of_company/main/view/MainStartScreen.kt
  feature/post/build.gradle.kts
  feature/profile/build.gradle.kts
  feature/signin/build.gradle.kts
  feature/signup/build.gradle.kts
  gradle/libs.versions.toml
Labels: 1️⃣ Priority: High, ♻️ Refactor

#120 🔀 :: (#119) - post part moshi converter error
  core/data/src/main/java/com/school_of_company/data/di/RepositoryModule.kt
  core/data/src/main/java/com/school_of_company/data/repository/main/MainRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/main/MainRepositoryImpl.kt
  core/data/src/main/java/com/school_of_company/data/repository/post/PostRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/post/PostRepositoryImpl.kt
  core/model/src/main/java/com/school_of_company/model/main/response/MainListResponseModel.kt
  core/model/src/main/java/com/school_of_company/model/post/response/PostListResponseModel.kt
  core/network/src/main/java/com/school_of_company/network/api/MainAPI.kt
  core/network/src/main/java/com/school_of_company/network/api/PostAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/main/MainDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/main/MainDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/datasource/post/PostDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/post/PostDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/di/NetworkModule.kt
  core/network/src/main/java/com/school_of_company/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/com/school_of_company/network/dto/main/reponse/MainListResponse.kt
  core/network/src/main/java/com/school_of_company/network/dto/post/response/PostListResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/main/reponse/MainListResponseMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/post/response/PostListResponseMapper.kt
  feature/main/src/main/java/com/school_of_company/main/component/MainList.kt
  feature/main/src/main/java/com/school_of_company/main/viewmodel/MainViewModel.kt
  feature/main/src/main/java/com/school_of_company/main/viewmodel/uistate/GetMainListUiState.kt
  feature/signin/src/main/java/com/school_of_company/signin/view/SignInScreen.kt
  feature/signin/src/main/java/com/school_of_company/signin/viewmodel/SignInViewModel.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#122 🔀 :: (#121) - notice 파트 네트워크 세팅을 하였습니다.
  core/data/src/main/java/com/school_of_company/data/di/RepositoryModule.kt
  core/data/src/main/java/com/school_of_company/data/repository/notice/NoticeRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/notice/NoticeRepositoryImpl.kt
  core/model/src/main/java/com/school_of_company/model/notice/.gitkeep
  core/model/src/main/java/com/school_of_company/model/notice/response/GetAllNoticeResponseModel.kt
  core/model/src/main/java/com/school_of_company/model/notice/response/GetSpecificNoticeResponseModel.kt
  core/network/src/main/java/com/school_of_company/network/api/NoticeAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/notice/NoticeDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/notice/NoticeDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/di/NetworkModule.kt
  core/network/src/main/java/com/school_of_company/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/com/school_of_company/network/dto/notice/.gitkeep
  core/network/src/main/java/com/school_of_company/network/dto/notice/response/GetAllNoticeResponse.kt
  core/network/src/main/java/com/school_of_company/network/dto/notice/response/GetSpecificNoticeResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/notice/.gitkeep
  core/network/src/main/java/com/school_of_company/network/mapper/notice/response/GetAllNoticecResponseMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/notice/response/GetSpecificNoticeResponseMapper.kt
Labels: 1️⃣ Priority: High, ⚙ Setting

#132 🔀 :: (#131) - Post 기능 게시글 조회, 특정 게시글 조회 기능을 구현하였습니다.
  app/src/main/java/com/school_of_company/gwangsan_android/navigation/GwangSanNavHost.kt
  core/data/src/main/java/com/school_of_company/data/repository/post/PostRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/post/PostRepositoryImpl.kt
  core/design-system/src/main/java/com/school_of_company/design_system/componet/recycle/CleaningRequestCard.kt
  core/design-system/src/main/java/com/school_of_company/design_system/componet/recycle/MyProfileUserLevel.kt
  core/model/src/main/java/com/school_of_company/model/post/response/PostListResponseModel.kt
  core/network/src/main/java/com/school_of_company/network/api/PostAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/post/PostDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/post/PostDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/dto/post/response/PostListResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/post/response/PostListResponseMapper.kt
  feature/content/build.gradle.kts
  feature/content/src/main/java/com/school_of_company/content/navigation/ContentNavigation.kt
  feature/content/src/main/java/com/school_of_company/content/view/ReadMoreScreen.kt
  feature/content/src/main/java/com/school_of_company/content/viewmodel/ContentViewModel.kt
  feature/content/src/main/java/com/school_of_company/content/viewmodel/uistate/GetSpecificPostUiState.kt
  feature/inform/src/main/java/com/school_of_company/inform/view/InformScreen.kt
  feature/main/src/main/java/com/school_of_company/main/component/MainList.kt
  feature/main/src/main/java/com/school_of_company/main/navgation/MainNavigation.kt
  feature/main/src/main/java/com/school_of_company/main/view/MainScreen.kt
  feature/main/src/main/java/com/school_of_company/main/view/MainStartScreen.kt
  feature/main/src/main/java/com/school_of_company/main/viewmodel/MainViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#139 🔀 :: (#115) - 리뷰 불러오기, 리뷰 작성 기능 구현
  app/src/main/java/com/school_of_company/gwangsan_android/navigation/GwangSanNavHost.kt
  core/data/src/main/java/com/school_of_company/data/di/RepositoryModule.kt
  core/data/src/main/java/com/school_of_company/data/repository/review/ReviewRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/review/ReviewRepositoryImpl.kt
  core/model/src/main/java/com/school_of_company/model/review/request/ReviewRequestModel.kt
  core/model/src/main/java/com/school_of_company/model/review/response/ReviewResponseModel.kt
  core/network/src/main/java/com/school_of_company/network/api/ReviewAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/review/ReviewDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/review/ReviewDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/di/NetworkModule.kt
  core/network/src/main/java/com/school_of_company/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/com/school_of_company/network/dto/review/request/ReviewRequest.kt
  core/network/src/main/java/com/school_of_company/network/dto/review/response/ReviewResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/review/request/ReviewRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/review/response/ReviewResponseMapper.kt
  feature/content/build.gradle.kts
  feature/content/src/main/java/com/school_of_company/content/view/ReadMoreScreen.kt
  feature/content/src/main/java/com/school_of_company/content/viewmodel/ContentViewModel.kt
  feature/content/src/main/java/com/school_of_company/content/viewmodel/uistate/ReviewPostUiState.kt
  feature/profile/build.gradle.kts
  feature/profile/src/main/java/com/school_of_company/profile/component/MyProfileReviewListItem.kt
  feature/profile/src/main/java/com/school_of_company/profile/navigation/MyProfileNavigation.kt
  feature/profile/src/main/java/com/school_of_company/profile/view/MyInformationEditScreen.kt
  feature/profile/src/main/java/com/school_of_company/profile/view/MyReceiveReviewScreen.kt
  feature/profile/src/main/java/com/school_of_company/profile/view/MyReviewLIstScreen.kt
  feature/profile/src/main/java/com/school_of_company/profile/view/OtherPersonProfile.kt
  feature/profile/src/main/java/com/school_of_company/profile/view/OtherReviewScreen.kt
  feature/profile/src/main/java/com/school_of_company/profile/viewmodel/MyProfileViewModel.kt
  feature/profile/src/main/java/com/school_of_company/profile/viewmodel/uistate/GetMyReviewUiState.kt
  feature/profile/src/main/java/com/school_of_company/profile/viewmodel/uistate/GetMyReviewWriteUiState.kt
  feature/profile/src/main/java/com/school_of_company/profile/viewmodel/uistate/OtherReviewUIState.kt
  feature/signup/src/main/java/com/school_of_company/signup/viewmodel/SignUpViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#150 🔀 :: (#143) - 공지, 메인 시작 화면에서 지점명을 표시해주었습니다.
  feature/inform/src/main/java/com/school_of_company/inform/view/InformScreen.kt
  feature/inform/src/main/java/com/school_of_company/inform/viewmodel/NoticeViewModel.kt
  feature/inform/src/main/java/com/school_of_company/inform/viewmodel/uistate/MemberUiState.kt
  feature/main/src/main/java/com/school_of_company/main/view/MainStartScreen.kt
  feature/main/src/main/java/com/school_of_company/main/viewmodel/MainViewModel.kt
  feature/main/src/main/java/com/school_of_company/main/viewmodel/uistate/MemberUiState.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#162 🔀 :: (#161) - 게시물 생성시 순서가 디자인과 달라 수정하였습니다.
  feature/post/src/main/java/com/school_of_company/post/view/PostScreen.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#169 🔀 :: (#168) - 채팅 기능 구현을 하기 위한 네트워크 세팅을 완료하였습니다.
  core/data/src/main/java/com/school_of_company/data/di/RepositoryModule.kt
  core/data/src/main/java/com/school_of_company/data/repository/chat/ChatRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/chat/ChatRepositoryImpl.kt
  core/model/src/main/java/com/school_of_company/model/chat/request/ReadMessageRequestModel.kt
  core/model/src/main/java/com/school_of_company/model/chat/response/GetChatMessageResponseModel.kt
  core/model/src/main/java/com/school_of_company/model/chat/response/GetChatRoomResponseModel.kt
  core/model/src/main/java/com/school_of_company/model/chat/response/JoinChatResponseModel.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/school_of_company/network/api/ChatAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/chat/ChatDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/chat/ChatDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/di/NetworkModule.kt
  core/network/src/main/java/com/school_of_company/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/com/school_of_company/network/dto/chat/request/ReadMessageRequest.kt
  core/network/src/main/java/com/school_of_company/network/dto/chat/response/GetChatMessageResponse.kt
  core/network/src/main/java/com/school_of_company/network/dto/chat/response/GetChatRoomResponse.kt
  core/network/src/main/java/com/school_of_company/network/dto/chat/response/JoinChatResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/chat/request/ReadMessageRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/chat/response/GetChatMessageResponseMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/chat/response/GetChatRoomResponseMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/chat/response/JoinChatResponseMapper.kt
  core/network/src/main/java/com/school_of_company/network/socket/dto/request/SendMessageDto.kt
  core/network/src/main/java/com/school_of_company/network/socket/dto/response/ChatMessageDto.kt
  core/network/src/main/java/com/school_of_company/network/socket/dto/response/RoomUpdateDto.kt
  core/network/src/main/java/com/school_of_company/network/socket/manager/SocketManager.kt
  core/network/src/main/java/com/school_of_company/network/socket/mapper/request/SendMessageMapper.kt
  core/network/src/main/java/com/school_of_company/network/socket/mapper/response/ChatMessageMapper.kt
  core/network/src/main/java/com/school_of_company/network/socket/mapper/response/RoomUpdateMapper.kt
  core/network/src/main/java/com/school_of_company/network/socket/model/request/SendMessage.kt
  core/network/src/main/java/com/school_of_company/network/socket/model/response/ChatMessage.kt
  core/network/src/main/java/com/school_of_company/network/socket/model/response/RoomUpdate.kt
  gradle/libs.versions.toml
Labels: 0️⃣ Priority: Critical, ⚙ Setting

#178 🔀 :: (#177) - 채팅방 목록 불러오기 API에 product 필드가 추가되어 반영 및 디자인 변경사항을 반영하였습니다.
  app/src/main/java/com/school_of_company/gwangsan_android/navigation/GwangSanNavHost.kt
  core/data/src/main/java/com/school_of_company/data/repository/chat/ChatRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/chat/ChatRepositoryImpl.kt
  core/model/src/main/java/com/school_of_company/model/chat/response/GetChatRoomResponseModel.kt
  core/network/src/main/java/com/school_of_company/network/datasource/chat/ChatDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/chat/ChatDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/dto/chat/response/GetChatRoomResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/chat/response/GetChatRoomResponseMapper.kt
  core/network/src/main/java/com/school_of_company/network/socket/manager/SocketManager.kt
  feature/chat/src/main/java/com/school_of_company/chat/component/ChatListItem.kt
  feature/chat/src/main/java/com/school_of_company/chat/navigation/ChatNavigation.kt
  feature/chat/src/main/java/com/school_of_company/chat/view/ChatRoomIdScreen.kt
  feature/chat/src/main/java/com/school_of_company/chat/view/ChatRoomScreen.kt
  feature/chat/src/main/java/com/school_of_company/chat/view/ChatScreen.kt
  feature/chat/src/main/java/com/school_of_company/chat/viewmodel/ChatViewModel.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor
