Repository School-of-Company/Gwangsan-Android, pull requests merged in 2025-06, with the labels that each got.

#32 🔀 :: (#31) gitignore 파일이 적용되지 않아 새로운 gitignore파일을 추가했습니다.
  .gitignore
Labels: 0️⃣ Priority: Critical

#37 🔀 :: (#36) - 회원가입 페이지 중 소개, 추천인 페이지 퍼블리싱을 하겠습니다
  core/design-system/src/main/java/com/school_of_company/design_system/componet/button/GwangSanButton.kt
  core/design-system/src/main/java/com/school_of_company/design_system/componet/dropdown/MultiSelectDropdown.kt
  core/design-system/src/main/java/com/school_of_company/design_system/componet/icons/GwangSanIcon.kt
  core/design-system/src/main/java/com/school_of_company/design_system/componet/topbar/GwangSanTopBar.kt
  core/design-system/src/main/java/com/school_of_company/design_system/theme/color/ColorTheme.kt
  core/design-system/src/main/java/com/school_of_company/design_system/theme/color/GwangSanColor.kt
  core/design-system/src/main/res/drawable/check.xml
  core/design-system/src/main/res/drawable/gwangsan.png
  feature/post/src/main/java/com/example/post/view/service/FinalPostScreen.kt
  feature/signup/src/main/java/com/school_of_company/signup/view/FinishScreen.kt
  feature/signup/src/main/java/com/school_of_company/signup/view/IntroduceScreen.kt
  feature/signup/src/main/java/com/school_of_company/signup/view/RecommderInputScreen.kt
Labels: ✨ Feature

#45 🔀 :: (::39) - myprofile navigation 세팅을 했습니다.
  feature/profile/build.gradle.kts
  feature/profile/src/main/java/com/school_of_company/profile/component/MyWriteList.kt
  feature/profile/src/main/java/com/school_of_company/profile/navigation/MyProfileNavigation.kt
  feature/profile/src/main/java/com/school_of_company/profile/view/MyProfileScreen.kt
  feature/profile/src/main/java/com/school_of_company/profile/view/MyReviewScreen.kt
  feature/profile/src/main/java/com/school_of_company/profile/view/MyWritingScreen.kt
  feature/profile/src/main/java/com/school_of_company/profile/view/MyWrtieDetailScreen.kt
  feature/profile/src/main/java/com/school_of_company/profile/view/TransactionHistoryScreen.kt
  feature/signup/src/main/java/com/school_of_company/signup/navigation/SignUpNavigation.kt
  feature/signup/src/main/java/com/school_of_company/signup/view/CertinSignUpScreen.kt
  feature/signup/src/main/java/com/school_of_company/signup/view/RecommenderInputScreen.kt
  gradle/libs.versions.toml
Labels: 1️⃣ Priority: High

#49 🔀 :: (#47) - Chatting page를 퍼블리싱 하였습니다.
  build-logic/convention/src/main/java/com/school_of_company/convention/gwangsan/KotlinAndroid.kt
  core/design-system/src/main/java/com/school_of_company/design_system/componet/button/GwangSanButton.kt
  core/design-system/src/main/java/com/school_of_company/design_system/componet/textfield/GwangSanTextField.kt
  core/design-system/src/main/res/drawable/rectangle.png
  feature/chat/.gitignore
  feature/chat/build.gradle.kts
  feature/chat/consumer-rules.pro
  feature/chat/proguard-rules.pro
  feature/chat/src/androidTest/java/com/school_of_company/chat/ExampleInstrumentedTest.kt
  feature/chat/src/main/AndroidManifest.xml
  feature/chat/src/main/java/com/school_of_company/chat/component/ChatListItem.kt
  feature/chat/src/main/java/com/school_of_company/chat/component/ChatMessageItem.kt
  feature/chat/src/main/java/com/school_of_company/chat/component/UnreadBadge.kt
  feature/chat/src/main/java/com/school_of_company/chat/view/ChatRoomScreen.kt
  feature/chat/src/main/java/com/school_of_company/chat/view/ChatScreen.kt
  feature/chat/src/test/java/com/school_of_company/chat/ExampleUnitTest.kt
  feature/signup/src/main/java/com/school_of_company/signup/view/CertinSignUpScreen.kt
  settings.gradle.kts
Labels: ✨ Feature

#55 🔀 :: (#53) - 스타트 페이지에 있는 이미지 변환을 구현했습니다.
  core/design-system/src/main/res/drawable/start1.png
  core/design-system/src/main/res/drawable/start2.png
  core/design-system/src/main/res/drawable/start3.png
  feature/signin/src/main/java/com/school_of_company/signin/navigation/LoginNavigation.kt
  feature/signin/src/main/java/com/school_of_company/signin/view/StartScreen.kt
Labels: 1️⃣ Priority: High

#59 🔀 :: (#58) 로그인 화면에도 바텀바가 보이는 것을 해결했습니다.
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/school_of_company/gwangsan_android/navigation/GwangSanNavHost.kt
  app/src/main/java/com/school_of_company/gwangsan_android/ui/GwangSanApp.kt
  app/src/main/res/values/strings.xml
  core/common/src/main/java/com/school_of_company/Regex/Regex.kt
  core/common/src/main/java/com/school_of_company/network/errorHandling.kt
  core/common/src/main/java/com/school_of_company/result/Result.kt
  core/data/build.gradle.kts
  core/data/src/androidTest/java/com/school_of_company/data/ExampleInstrumentedTest.kt
  core/data/src/main/java/com/school_of_company/data/di/RepositoryModule.kt
  core/data/src/main/java/com/school_of_company/data/repository/AuthRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/AuthRepositoryImpl.kt
  core/design-system/src/main/java/com/school_of_company/design_system/componet/toast/MakeToast.kt
  core/design-system/src/main/res/values/res.xml
  core/design-system/src/main/res/values/strings.xml
  core/network/src/main/java/com/school_of_company/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/di/NetworkModule.kt
  core/network/src/main/java/com/school_of_company/network/dto/auth/reponse/LoginResponse.kt
  core/network/src/main/java/com/school_of_company/network/dto/auth/requset/SignUpRequest.kt
  core/network/src/main/java/com/school_of_company/network/mapper/auth/request/LoginRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/auth/request/SignUpRequestMapper.kt
  core/network/src/main/java/com/school_of_company/network/mapper/auth/response/LoginResposeMapper.kt
  feature/signin/build.gradle.kts
  feature/signin/src/main/java/com/school_of_company/signin/navigation/LoginNavigation.kt
  feature/signin/src/main/java/com/school_of_company/signin/view/SignInScreen.kt
  feature/signin/src/main/java/com/school_of_company/signin/viewmodel/SignInViewModel.kt
  feature/signin/src/main/java/com/school_of_company/signin/viewmodel/uistate/SaveTokenUiState.kt
  feature/signin/src/main/java/com/school_of_company/signin/viewmodel/uistate/SignInUiState.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 1️⃣ Priority: High, 🐞 Bug

#68 🔀 :: (#65) - 메인 리스트를 구현했습니다.
  app/src/main/java/com/school_of_company/gwangsan_android/navigation/GwangSanNavHost.kt
  core/data/src/main/java/com/school_of_company/data/di/RepositoryModule.kt
  core/data/src/main/java/com/school_of_company/data/repository/main/MainRepository.kt
  core/data/src/main/java/com/school_of_company/data/repository/main/MainRepositoryImpl.kt
  core/design-system/src/main/java/com/school_of_company/design_system/componet/icons/GwangSanIcon.kt
  core/design-system/src/main/res/drawable/main.png
  core/design-system/src/main/res/drawable/mdi_bell_outline.xml
  core/design-system/src/main/res/drawable/name.xml
  core/design-system/src/main/res/drawable/service.png
  core/design-system/src/main/res/values/strings.xml
  core/model/build.gradle.kts
  core/model/src/main/java/com/school_of_company/model/enum/Mode.kt
  core/model/src/main/java/com/school_of_company/model/enum/Type.kt
  core/model/src/main/java/com/school_of_company/model/main/response/MainListResponseModel.kt
  core/network/src/main/java/com/school_of_company/network/api/MainAPI.kt
  core/network/src/main/java/com/school_of_company/network/datasource/main/MainDataSource.kt
  core/network/src/main/java/com/school_of_company/network/datasource/main/MainDataSourceImpl.kt
  core/network/src/main/java/com/school_of_company/network/di/NetworkModule.kt
  core/network/src/main/java/com/school_of_company/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/com/school_of_company/network/dto/main/reponse/MainListResponse.kt
  core/network/src/main/java/com/school_of_company/network/mapper/main/reponse/MainListResponseMapper.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/school_of_company/main/component/MainList.kt
  feature/main/src/main/java/com/school_of_company/main/navgation/MainNavigation.kt
  feature/main/src/main/java/com/school_of_company/main/view/MainScreen.kt
  feature/main/src/main/java/com/school_of_company/main/view/MainStartScreen.kt
  feature/main/src/main/java/com/school_of_company/main/viewmodel/MainViewModel.kt
  feature/main/src/main/java/com/school_of_company/main/viewmodel/uistate/GetMainListUiState.kt
  feature/signin/src/main/java/com/school_of_company/signin/view/SignInScreen.kt
  gradle/libs.versions.toml
Labels: 1️⃣ Priority: High

#72 🔀 :: (#71) - 회원가입 페이지 ErrorToast추가
  app/src/main/java/com/school_of_company/gwangsan_android/navigation/GwangSanNavHost.kt
  core/design-system/src/main/res/values/strings.xml
  feature/signin/src/main/java/com/school_of_company/signin/view/SignInScreen.kt
  feature/signup/src/main/java/com/school_of_company/signup/navigation/SignUpNavigation.kt
  feature/signup/src/main/java/com/school_of_company/signup/view/IntroduceScreen.kt
  feature/signup/src/main/java/com/school_of_company/signup/view/RecommenderInputScreen.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#74 🔀 :: (#73) - Post page에 navigation setting을 했습니다.
  feature/post/build.gradle.kts
  feature/post/src/main/java/com/school_of_company/post/navigation/PostNavigation.kt
  feature/post/src/main/java/com/school_of_company/post/view/FinalPostScreen.kt
  feature/post/src/main/java/com/school_of_company/post/view/PostInputScreen.kt
  feature/post/src/main/java/com/school_of_company/post/view/PostWriteScreen.kt
Labels: ✨ Feature

#83 🔀 :: (#82) - StartScreen 부분에 디자인과 다른 부분이 존재하여 수정하였습니다.
  core/design-system/src/main/java/com/school_of_company/design_system/componet/button/GwangSanButton.kt
  feature/signin/src/main/java/com/school_of_company/signin/view/StartScreen.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#86 🔀 :: (#85) - indicato애 정렬을 맞췄습니다.
  feature/signin/src/main/java/com/school_of_company/signin/view/StartScreen.kt
Labels: 1️⃣ Priority: High

#87 🔀 :: (#84) - chat 모듈 리팩터링을 진행하였습니다.
  feature/chat/src/main/java/com/school_of_company/chat/component/ChatListItem.kt
  feature/chat/src/main/java/com/school_of_company/chat/component/ChatMessageItem.kt
  feature/chat/src/main/java/com/school_of_company/chat/component/UnreadBadge.kt
  feature/chat/src/main/java/com/school_of_company/chat/view/ChatRoomScreen.kt
  feature/chat/src/main/java/com/school_of_company/chat/view/ChatScreen.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor
